### ISSUE TITLE
`nocite`s not rendered

### ISSUE THREAD

**Issue by njbart** [odkr/pandoc-zotxt.lua#7]
Citekeys placed in a `nocite` pandoc metadata field are not being rendered if using pandoc-zotxt.lua.

**Example, using `cite`** (with Zotero running, and containing a `@brush:ornithology` item):

```
pandoc --lua-filter pandoc-zotxt.lua -C -t plain << EOT
@brush:ornithology
EOT
```

actual = expected output:

```
Brush and Clark (1983)

Brush, A. H., and G. A. Clark Jr., eds. 1983. Perspectives in
Ornithology. Cambridge: Cambridge Univ. Press.
```

**using `nocite`:**

```
pandoc --lua-filter pandoc-zotxt.lua -C -t plain << EOT
---
nocite: '@brush:ornithology'
...
EOT
```

Actual output: nothing

Expected:

```
Brush, A. H., and G. A. Clark Jr., eds. 1983. Perspectives in
Ornithology. Cambridge: Cambridge Univ. Press.
```

**For comparison, biblio data in pandoc metadata:**

```
pandoc -C -t plain << EOT
---
nocite: '@brush:ornithology'
references:
- id: brush:ornithology
  editor:
    - family: Brush
      given: A. H.
    - family: Clark
      given: G. A.
      suffix: Jr.
  issued: 1983
  language: en-GB
  publisher: Cambridge Univ. Press
  publisher-place: Cambridge
  title: Perspectives in ornithology
  type: book
...
EOT
```

actual = expected output:

```
Brush, A. H., and G. A. Clark Jr., eds. 1983. Perspectives in
Ornithology. Cambridge: Cambridge Univ. Press.
```

I'd be happy to investigate further, e.g., how exactly nocites are represented in the pandoc AST, but maybe that isn't necessary, and there's an immediately obvious solution. Just let me know.
